In [1]:
import numpy as np

In [3]:
one_dimensional_array = np.array([1.2,2.4,3.5,4.7,6.1,7.2,8.3,9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [5]:
two_dimensional_array = np.array([[6,5],[11,7],[4,8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [7]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
array_zeros = np.zeros([3,2])
print(array_zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
array_ones = np.ones([3,2])
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
sequences_of_integer = np.arange(5,12)
print(sequences_of_integer)

[ 5  6  7  8  9 10 11]


In [16]:
random_integers_between_50_and_100 = np.random.randint(low=50,high=101,size=(6))
print(random_integers_between_50_and_100)

[91 67 55 60 83 68]


In [17]:
random_float_between_0_and_1 = np.random.random([6])
print(random_float_between_0_and_1)

[0.96079706 0.83818703 0.46537882 0.90921294 0.66490244 0.02525624]


In [21]:
print("Task 1: Create a Linear Dataset")
print("Your goal is to create a simple dataset consisting of a single feature and a label as follows:")
print("1. Assign a squence of integers from 6 to 20 (inslusive) to NumPy array named feature.")
print("2. Assign 15 values to a NumPy array named label such that:")
print("label = (3)(feature) + 4")
print("label = (3)(6) + 4 = 22")

Task 1: Create a Linear Dataset
Your goal is to create a simple dataset consisting of a single feature and a label as follows:
1. Assign a squence of integers from 6 to 20 (inslusive) to NumPy array named feature.
2. Assign 15 values to a NumPy array named label such that:
label = (3)(feature) + 4
label = (3)(6) + 4 = 22


In [23]:
feature = np.arange(6,21)
print("feature : ")
print(feature)
label = 3*feature + 4
print("label : ")
print(label)


feature : 
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
label : 
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [26]:
print("Task 2 : Add Some Noise to the Dataset")
print("To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created.")
print("To be more pprecise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.")
print("Don't rely in broadcasting. Instead, create a noise array having the same dimension as label.")

Task 2 : Add Some Noise to the Dataset
To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created.
To be more pprecise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.
Don't rely in broadcasting. Instead, create a noise array having the same dimension as label.


In [27]:
noise = np.random.random(15)*4 - 2 #(0,1)*4 -2 = (0,4)-2 = (-2,2)
print(noise)
label = label + noise
print(label)

[ 1.0301423  -1.78295892 -0.83745852  0.71253722 -1.12058424 -1.84266593
 -0.77580887  0.25759419 -0.43272208  0.49071947 -1.3546317   0.23418048
  1.32649785  0.04999316 -0.38675153]
[23.49213945 21.5665226  25.20857679 31.64439895 32.07622741 36.0462764
 37.88751482 44.51630702 46.88333623 51.00701401 51.82736204 56.33381512
 59.30558904 59.48591691 65.27892111]
